language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script: composer install

script:
  - phpunit --testsuite travis-ci
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
